import type { InventoryItem, JobAssignment, UsageHistoryEntry } from "./types";
import chairImage from "./assets/bf3e3b2adbbf51a3685ccb430cd7f99f62425330.png";
import rugImage from "./assets/f5a2d9644fffe5e34bfd23da01cfaaa2b7ee4a7a.png";
import pillowImage from "./assets/76b3695f8fd53782b957f65619ca621ff4a6454e.png";
import platformBedImage from "./assets/a76222775f9255aefbcfeeda97001c3a2820fb74.png";
import canopyBedImage from "./assets/1c9a524adaf9b26f3aa98a6f97f0fdfa9b9f19d5.png";
import wovemRugImage from "./assets/2c489e62b99b8b4f0d5e5eca8520aa88995ac72b.png";
import barCartImage from "./assets/7c88476d06e9bfb8e21678c9b9ce829a2c9129da.png";
import armchairImage from "./assets/c3b1c63e16e2d237b57944514c694ba376985843.png";
import consoleTableImage from "./assets/67f78ca9032fd1a83ab0f0b38575245e8a147f0c.png";
import oliveTreeImage from "./assets/c47166bb3e07ff395671cb27cc14e05ec42d5841.png";
import whiteOfficeChairImage from "./assets/99b2052cbb92f7d5d277ffd1cff1035b0102207f.png";
import brassFloorLampImage from "./assets/690d82d765bc87a642e654c45ff62e78d98609e6.png";

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "2",
    name: "Modern Lounge Chair",
    category: "Furniture",
    location: "Warehouse B - Section 1",
    purchaseCost: 459,
    totalQuantity: 20,
    inUseQuantity: 18,
    availableQuantity: 2,
    tags: ["chair", "lounge", "modern", "seating", "furniture"],
    imageUrl: chairImage,
    usageCount: 50,
    dateAdded: new Date("2024-02-10"),
    lastUsed: new Date("2024-10-26"),
  },
  {
    id: "4",
    name: "Natural Jute Area Rug",
    category: "Decor",
    location: "Warehouse C - Section 2",
    purchaseCost: 189,
    totalQuantity: 25,
    inUseQuantity: 20,
    availableQuantity: 5,
    tags: ["rug", "jute", "natural", "flooring", "decor"],
    imageUrl: rugImage,
    usageCount: 49,
    dateAdded: new Date("2024-03-05"),
    lastUsed: new Date("2024-10-23"),
  },
  {
    id: "16",
    name: "Velvet Throw Pillow",
    category: "Decor",
    location: "Warehouse B - Section 2",
    purchaseCost: 45,
    totalQuantity: 50,
    inUseQuantity: 38,
    availableQuantity: 12,
    tags: ["pillow", "velvet", "throw", "decor", "soft", "cushion"],
    imageUrl: pillowImage,
    usageCount: 52,
    dateAdded: new Date("2024-02-20"),
    lastUsed: new Date("2024-10-27"),
  },
  {
    id: "17",
    name: "Natural Oak Platform Bed",
    category: "Furniture",
    location: "Warehouse A - Section 2",
    purchaseCost: 1299,
    totalQuantity: 10,
    inUseQuantity: 7,
    availableQuantity: 3,
    tags: ["bed", "platform", "oak", "furniture", "bedroom", "wood", "queen"],
    imageUrl: platformBedImage,
    usageCount: 18,
    dateAdded: new Date("2024-05-10"),
    lastUsed: new Date("2024-10-26"),
  },
  {
    id: "18",
    name: "Classic Canopy Bed Frame",
    category: "Furniture",
    location: "Warehouse A - Section 2",
    purchaseCost: 1899,
    totalQuantity: 6,
    inUseQuantity: 4,
    availableQuantity: 2,
    tags: ["bed", "canopy", "four-poster", "furniture", "bedroom", "wood", "elegant"],
    imageUrl: canopyBedImage,
    usageCount: 15,
    dateAdded: new Date("2024-06-20"),
    lastUsed: new Date("2024-10-24"),
  },
  {
    id: "19",
    name: "Geometric Woven Area Rug",
    category: "Decor",
    location: "Warehouse C - Section 1",
    purchaseCost: 229,
    totalQuantity: 18,
    inUseQuantity: 13,
    availableQuantity: 5,
    tags: ["rug", "woven", "geometric", "natural", "jute", "decor", "flooring"],
    imageUrl: wovemRugImage,
    usageCount: 40,
    dateAdded: new Date("2024-07-15"),
    lastUsed: new Date("2024-10-27"),
  },
  {
    id: "20",
    name: "Brass Bar Cart",
    category: "Furniture",
    location: "Warehouse B - Section 3",
    purchaseCost: 549,
    totalQuantity: 12,
    inUseQuantity: 9,
    availableQuantity: 3,
    tags: ["cart", "bar", "brass", "gold", "glass", "furniture", "entertaining", "storage"],
    imageUrl: barCartImage,
    usageCount: 48,
    dateAdded: new Date("2024-08-01"),
    lastUsed: new Date("2024-10-26"),
  },
  {
    id: "21",
    name: "Upholstered Swivel Armchair",
    category: "Furniture",
    location: "Warehouse A - Section 1",
    purchaseCost: 699,
    totalQuantity: 14,
    inUseQuantity: 11,
    availableQuantity: 3,
    tags: ["chair", "armchair", "swivel", "upholstered", "seating", "furniture", "brown"],
    imageUrl: armchairImage,
    usageCount: 52,
    dateAdded: new Date("2024-08-15"),
    lastUsed: new Date("2024-10-27"),
  },
  {
    id: "22",
    name: "Classic Console Table",
    category: "Furniture",
    location: "Warehouse C - Section 4",
    purchaseCost: 449,
    totalQuantity: 10,
    inUseQuantity: 6,
    availableQuantity: 4,
    tags: ["table", "console", "entryway", "furniture", "storage", "drawer", "black", "wood"],
    imageUrl: consoleTableImage,
    usageCount: 48,
    dateAdded: new Date("2024-09-01"),
    lastUsed: new Date("2024-10-25"),
  },
  {
    id: "23",
    name: "Faux Olive Tree",
    category: "Decor",
    location: "Warehouse B - Section 4",
    purchaseCost: 189,
    totalQuantity: 15,
    inUseQuantity: 10,
    availableQuantity: 5,
    tags: ["plant", "tree", "olive", "faux", "artificial", "decor", "greenery", "tall"],
    imageUrl: oliveTreeImage,
    usageCount: 28,
    dateAdded: new Date("2024-09-15"),
    lastUsed: new Date("2024-10-26"),
  },
  {
    id: "24",
    name: "Executive Office Chair",
    category: "Furniture",
    location: "Warehouse A - Section 1",
    purchaseCost: 399,
    totalQuantity: 20,
    inUseQuantity: 16,
    availableQuantity: 4,
    tags: ["chair", "office", "executive", "white", "swivel", "adjustable", "seating", "furniture"],
    imageUrl: whiteOfficeChairImage,
    usageCount: 35,
    dateAdded: new Date("2024-09-20"),
    lastUsed: new Date("2024-10-27"),
  },
  {
    id: "25",
    name: "Modern Brass Floor Lamp",
    category: "Lighting",
    location: "Warehouse C - Section 3",
    purchaseCost: 329,
    totalQuantity: 18,
    inUseQuantity: 14,
    availableQuantity: 4,
    tags: ["lamp", "floor", "brass", "gold", "modern", "lighting", "adjustable", "LED"],
    imageUrl: brassFloorLampImage,
    usageCount: 32,
    dateAdded: new Date("2024-09-25"),
    lastUsed: new Date("2024-10-25"),
  },
];

// Helper function to get dates relative to today
const getRelativeDate = (daysFromNow: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date;
};

export const mockJobAssignments: JobAssignment[] = [
  {
    id: "a2",
    itemId: "2",
    jobLocation: "3315 Old Creek Rd, Gilroy",
    startDate: getRelativeDate(-30),
    endDate: getRelativeDate(15),
    quantity: 12,
    notes: "Executive lounge area",
    assignedBy: "John Doe",
    status: "active",
    stagingDate: getRelativeDate(-22),
    stagingStatus: "staged",
    clientName: "Madison Donaldson",
    shortAddress: "Old Creek rd",
    fullAddress: "3315 Old Creek Rd, Gilroy",
    itemIds: ["21", "4", "19", "22", "2", "16"],
  },
  {
    id: "a3",
    itemId: "4",
    jobLocation: "1515 Pine Lake Rd, Sammamish, WA",
    startDate: getRelativeDate(-28),
    endDate: getRelativeDate(17),
    quantity: 8,
    notes: "Living room display",
    assignedBy: "Jane Smith",
    status: "active",
    stagingDate: getRelativeDate(-23),
    stagingStatus: "staged",
    clientName: "Julian Lee",
    shortAddress: "Pine Lake rd",
    fullAddress: "1515 Pine Lake Rd, Sammamish, WA",
    itemIds: ["2", "21", "22", "17", "20", "4"],
  },
  {
    id: "a4",
    itemId: "16",
    jobLocation: "1004 Pine Crest Ave, Issaquah",
    startDate: getRelativeDate(-5),
    endDate: getRelativeDate(40),
    quantity: 15,
    notes: "Guest room decor package",
    assignedBy: "Sarah Johnson",
    status: "active",
    stagingDate: getRelativeDate(-2),
    stagingStatus: "staged",
    clientName: "Lauren Ann",
    shortAddress: "Pine crest",
    fullAddress: "1004 Pine Crest Ave, Issaquah",
    itemIds: ["2", "4", "19", "22", "16", "21"],
  },
  {
    id: "a5",
    itemId: "20",
    jobLocation: "2200 Harbor View Dr, Seattle, WA",
    startDate: getRelativeDate(10),
    endDate: getRelativeDate(40),
    quantity: 2,
    notes: "High-end staging for sale",
    assignedBy: "Mike Chen",
    status: "active",
    stagingDate: getRelativeDate(8),
    stagingStatus: "upcoming",
    clientName: "Sarah Mitchell",
    shortAddress: "Harbor View",
    fullAddress: "2200 Harbor View Dr, Seattle, WA",
    itemIds: [],
  },
  {
    id: "a6",
    itemId: "21",
    jobLocation: "5500 Tech Plaza Blvd, Redmond, WA",
    startDate: getRelativeDate(15),
    endDate: getRelativeDate(50),
    quantity: 8,
    notes: "Board room furniture setup",
    assignedBy: "Emily Rodriguez",
    status: "active",
    stagingDate: getRelativeDate(12),
    stagingStatus: "upcoming",
    clientName: "Robert Chen",
    shortAddress: "Tech Plaza",
    fullAddress: "5500 Tech Plaza Blvd, Redmond, WA",
    itemIds: [],
  },
];

export const mockUsageHistory: UsageHistoryEntry[] = [
  {
    id: "h1",
    itemId: "2",
    date: getRelativeDate(-15),
    action: "assigned",
    user: "John Doe",
    quantity: 12,
  },
  {
    id: "h2",
    itemId: "4",
    date: getRelativeDate(-12),
    action: "assigned",
    jobLocation: "1515 Pine Lake Rd, Sammamish, WA",
    user: "Jane Smith",
    quantity: 8,
  },
  {
    id: "h3",
    itemId: "2",
    date: getRelativeDate(-264),
    action: "added",
    user: "John Doe",
    quantity: 20,
  },
];
